/*
 * Dodo Global API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dodo

type MonthTotalRevenueModel struct {
	CountryId int32 `json:"countryId,omitempty"`
	CountryCode string `json:"countryCode,omitempty"`
	Currency string `json:"currency,omitempty"`
	Revenue float64 `json:"revenue,omitempty"`
}
