/*
 * Dodo Global API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dodo

type AddressModel struct {
	Text string `json:"text,omitempty"`
	Locality *LocalityModel `json:"locality,omitempty"`
	Street *StreetModel `json:"street,omitempty"`
	House *HouseModel `json:"house,omitempty"`
}
