/*
 * Dodo Global API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dodo

type ProductImage struct {
	Size int32 `json:"size,omitempty"`
	Urls []string `json:"urls,omitempty"`
}
