/*
 * Dodo Global API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dodo

type MetricsModel struct {
	UnitId int32 `json:"unitId,omitempty"`
	Revenue float64 `json:"revenue,omitempty"`
	Count int32 `json:"count,omitempty"`
	StationaryRevenue float64 `json:"stationaryRevenue,omitempty"`
	StationaryCount int32 `json:"stationaryCount,omitempty"`
	DeliveryRevenue float64 `json:"deliveryRevenue,omitempty"`
	DeliveryCount int32 `json:"deliveryCount,omitempty"`
	PickupRevenue float64 `json:"pickupRevenue,omitempty"`
	PickupCount int32 `json:"pickupCount,omitempty"`
	StationaryMobileRevenue float64 `json:"stationaryMobileRevenue,omitempty"`
	StationaryMobileCount int32 `json:"stationaryMobileCount,omitempty"`
	DeliveryMobileRevenue float64 `json:"deliveryMobileRevenue,omitempty"`
	DeliveryMobileCount int32 `json:"deliveryMobileCount,omitempty"`
	PickupMobileRevenue float64 `json:"pickupMobileRevenue,omitempty"`
	PickupMobileCount int32 `json:"pickupMobileCount,omitempty"`
}
