/*
 * Dodo Global API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dodo

type OrdersCountBySourceStatistics struct {
	OrdersCountByPhone int32 `json:"ordersCountByPhone,omitempty"`
	OrdersCountBySite int32 `json:"ordersCountBySite,omitempty"`
	OrdersCountByRestaurant int32 `json:"ordersCountByRestaurant,omitempty"`
	OrdersCountByDefectOrder int32 `json:"ordersCountByDefectOrder,omitempty"`
	OrdersCountByMobile int32 `json:"ordersCountByMobile,omitempty"`
	OrdersCountByPizzeria int32 `json:"ordersCountByPizzeria,omitempty"`
	OrdersCountByAggregator int32 `json:"ordersCountByAggregator,omitempty"`
	TotalCount int32 `json:"totalCount,omitempty"`
}
