/*
 * Dodo Global API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dodo

type WorkTimeModel struct {
	Start int32 `json:"start,omitempty"`
	End int32 `json:"end,omitempty"`
}
