/*
 * Dodo Global API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dodo

type UnitModel struct {
	Id int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Uuid string `json:"uuid,omitempty"`
	Alias string `json:"alias,omitempty"`
	StartDate string `json:"startDate,omitempty"`
	TimeZoneShift int32 `json:"timeZoneShift,omitempty"`
	WebcamUrl string `json:"webcamUrl,omitempty"`
	Coords *CoordinatesModel `json:"coords,omitempty"`
	Address *AddressModel `json:"address,omitempty"`
	Stationary *ScheduleModel `json:"stationary,omitempty"`
	Delivery *ScheduleModel `json:"delivery,omitempty"`
}
