/*
 * Dodo Global API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dodo

type TotalRevenueModel struct {
	Year int32 `json:"year,omitempty"`
	Month int32 `json:"month,omitempty"`
	Currency string `json:"currency,omitempty"`
	Revenue float64 `json:"revenue,omitempty"`
}
