/*
 * Dodo Global API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dodo

type StreetModel struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Type_ string `json:"type,omitempty"`
	TypeName string `json:"typeName,omitempty"`
	TypeAbbr string `json:"typeAbbr,omitempty"`
}
