/*
 * Dodo Global API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dodo

type ProductStatistic struct {
	Name string `json:"name,omitempty"`
	OrdersCount int32 `json:"ordersCount,omitempty"`
	Images []ProductImage `json:"images,omitempty"`
}
