/*
 * Dodo Global API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dodo

type WeekRevenueHistoryModel struct {
	CountryId int32 `json:"countryId,omitempty"`
	CountryCode string `json:"countryCode,omitempty"`
	UnitId int32 `json:"unitId,omitempty"`
	Weeks []WeekRevenueModel `json:"weeks,omitempty"`
}
