/*
 * Dodo Global API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dodo

type Rating struct {
	UnitUUId string `json:"unitUUId,omitempty"`
	AvgServiceTime int32 `json:"avgServiceTime,omitempty"`
	SummaryRates int32 `json:"summaryRates,omitempty"`
	FeedbackQty int32 `json:"feedbackQty,omitempty"`
	AvgRating float64 `json:"avgRating,omitempty"`
	AvgCookingTime int32 `json:"avgCookingTime,omitempty"`
}
