/*
 * Dodo Global API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dodo
import (
	"time"
)

type WeekRevenueModel struct {
	StartDay time.Time `json:"startDay,omitempty"`
	EndDay time.Time `json:"endDay,omitempty"`
	Revenue float64 `json:"revenue,omitempty"`
	Count int32 `json:"count,omitempty"`
	DeliveryRevenue float64 `json:"deliveryRevenue,omitempty"`
	DeliveryCount int32 `json:"deliveryCount,omitempty"`
	StationaryRevenue float64 `json:"stationaryRevenue,omitempty"`
	StationaryCount int32 `json:"stationaryCount,omitempty"`
	PickupRevenue float64 `json:"pickupRevenue,omitempty"`
	PickupCount int32 `json:"pickupCount,omitempty"`
	WeekId int32 `json:"weekId,omitempty"`
}
