/*
 * Dodo Global API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dodo

type WeeklyTopModelBrandData struct {
	Countries []WeeklyTopModel `json:"countries,omitempty"`
	Errors []ErrorModel `json:"errors,omitempty"`
	Brand string `json:"brand,omitempty"`
}
