/*
 * Dodo Global API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dodo

type StatisticsModel struct {
	CountryId int32 `json:"countryId,omitempty"`
	CountryCode string `json:"countryCode,omitempty"`
	UnitId int32 `json:"unitId,omitempty"`
	Date string `json:"date,omitempty"`
	StationaryRevenue float64 `json:"stationaryRevenue,omitempty"`
	StationaryOrderCount int32 `json:"stationaryOrderCount,omitempty"`
	DeliveryRevenue float64 `json:"deliveryRevenue,omitempty"`
	DeliveryOrderCount int32 `json:"deliveryOrderCount,omitempty"`
	Revenue float64 `json:"revenue,omitempty"`
	OrderCount int32 `json:"orderCount,omitempty"`
	AvgCheck float64 `json:"avgCheck,omitempty"`
}
